### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by smeetvaghani** [Bhitt/Unity_2D_Projects#1]
hello i need this course can you provide me this course?

**Comment by Bhitt** [comment]
@smeetvaghani 
[Complete C# Unity Game Developer 2D](https://www.udemy.com/share/101Wjs/ )
and/or [The Ultimate Guide to Game Development with Unity (Official)](https://www.udemy.com/share/101WZg/)
Both courses regularly go on sale for around $15 (US)
